#!/bin/sh

# use linux_base's sh to fake uname

ARCH=`uname -p`

if [ "${ARCH}" = "amd64" -a -z "${FORCE}" ]; then
	echo "MATLAB can not run on amd64. To try it, run"
	echo ""
	echo "env FORCE=1 $0 "
	exit 1
fi

echo ""
echo "!!! WARNING !!!"
echo ""
echo "Running MATLAB on FreeBSD is considered as experimental."
echo "This is not officially supported by the MathWorks, Inc."
echo ""
echo "!!! WARNING !!!"
echo ""

sleep 1

exec /compat/linux/bin/sh /compat/linux/usr/local/matlab/bin/matlab "$@"
