# New ports collection makefile for:	local/wdm
# Date created:				Apr 19 2006
# Whom:					Rong-En Fan <rafan@infor.org>
#
# $FreeBSD$
#

CATEGORIES=	local

MAINTAINER=	rafan@infor.org
COMMENT=	x11/wdm with 217 patches

CONFLICTS=	wdm-[0-9]*

MASTERDIR=	${.CURDIR}/../../x11/wdm

EXTRA_PATCHES=	${.CURDIR}/files/patch-*

.include "${MASTERDIR}/Makefile"
