# New ports collection makefile for:	local/mlterm
# Date created:				Apr 20 2006
# Whom:					Rong-En Fan <rafan@csie.ntu.edu.tw>
#
# $FreeBSD$
#

CATEGORIES=	local

MAINTAINER=	rafan@csie.ntu.edu.tw
COMMENT=	x11/mlterm with 217 patches

CONFLICTS=	mlterm-[0-9]*

MASTERDIR=	${.CURDIR}/../../x11/mlterm

EXTRA_PATCHES=	${.CURDIR}/files/patch-*

.include "${MASTERDIR}/Makefile"

