# New ports collection makefile for:	local/icewm
# Date created:				Apr 24 2006
# Whom:					Rong-En Fan <rafan@infor.org>
#
# $FreeBSD$
#

CATEGORIES=	local

MAINTAINER=	rafan@infor.org
COMMENT=	x11-wm/icewm with 217 patches

CONFLICTS=	icewm-*

MASTERDIR=	${.CURDIR}/../../x11-wm/icewm

EXTRA_PATCHES=	${.CURDIR}/files/patch-*

.include "${MASTERDIR}/Makefile"
