# New ports collection makefile for:	local/icewm
# Date created:				Apr 24 2006
# Whom:					Rong-En Fan <rafan@csie.ntu.edu.tw>
#
# $FreeBSD$
#

CATEGORIES=	local

MAINTAINER=	rafan@csie.ntu.edu.tw
COMMENT=	x11-wm/icewm with 217 patches

CONFLICTS=	icewm-*

MASTERDIR=	${.CURDIR}/../../x11-wm/icewm

EXTRA_PATCHES=	${.CURDIR}/files/patch-*

.include "${MASTERDIR}/Makefile"
