# New ports collection makefile for:	local/windowmaker
# Date created:				Apr 24 2006
# Whom:					Rong-En Fan <rafan@infor.org>
#
# $FreeBSD$
#

CATEGORIES=	local

MAINTAINER=	rafan@infor.org
COMMENT=	x11-wm/windowmaker with 217 patches

CONFLICTS=	windowmaker-*

MASTERDIR=	${.CURDIR}/../../x11-wm/windowmaker

EXTRA_PATCHES=	${.CURDIR}/files/patch-*

.include "${MASTERDIR}/Makefile"
