# New ports collection makefile for:	local/joe
# Date created:				Apr 20 2006
# Whom:					Rong-En Fan <rafan@infor.org>
#
# $FreeBSD$
#

CATEGORIES=	local

MAINTAINER=	rafan@infor.org
COMMENT=	editors/joe with 217 patches

CONFLICTS=	joe-[0-9]*

MASTERDIR=	${.CURDIR}/../../editors/joe

EXTRA_PATCHES=	${.CURDIR}/files/patch-*

.include "${MASTERDIR}/Makefile"
