# New ports collection makefile for:	local/rxvt-devel
# Date created:				Apr 22 2006
# Whom:					Rong-En Fan <rafan@csie.ntu.edu.tw>
#
# $FreeBSD$
#

CATEGORIES=	local

MAINTAINER=	ta@csie.ntu.edu.tw
COMMENT=	x11/rxvt-devel with 217 patches

CONFLICTS=	rxvt-devel-[0-9]*

MASTERDIR=	${.CURDIR}/../../x11/rxvt-devel

EXTRA_PATCHES=	${.CURDIR}/files/patch-*

WITH_XGETDEFAULT=	yes

.include "${MASTERDIR}/Makefile"
